### PR TITLE
Use `generateBundle` instead of `onwrite`

### PR DESCRIPTION
**Pull request by doktordata**
Fix for #3

### CODE REVIEW

**Comment by haifeng2013** [comment]
@doktordata Thanks for your pr and sorry for the late response. Yes, we need to switch to generateBundle.

however, I believe we cannot simply replace onwrite by generateBundle, as "onwrite" is executed "after the file has been written to disk.", and "generateBundle" is executed " immediately before the files are written in bundle.write()".

And this plugin actually needs to read the generated file on disk and insert it into HTML file.

**Comment by r0skar** [comment]
I think we should use the `writeBundle` hook.

> Called only at the end of bundle.write() once all files have been written. Similar to the generateBundle hook, bundle provides the full list of files being written along with their details.

**Comment by haifeng2013** [comment]
@r0skar you are probably right ;)

**Comment by haifeng2013** [comment]
onwrite hook is replaced, close this pr.

**Pull request closed without merging**
